workspace(name = "bazel_bazed_project")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "catch2",
    strip_prefix = "Catch2-2.13.7",
    urls = ["https://github.com/catchorg/Catch2/archive/v2.13.7.tar.gz"],
)

